services:
  backend:
    build: ./backend
    image: form-craft-backend
    ports:
      - '5001:5000'
    networks:
      - my_network
    env_file:
      - ./backend/.env
    # healthcheck:
    #   test: ['CMD', 'curl', '-f', 'http://localhost:5000']
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  frontend:
    build: ./frontend
    image: form-craft-frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

    # docker-compose down
# docker-compose up --build

# http://localhost:5001/api/message

# http://localhost:3000/
