version: '3.8'
services:
  backend:
    image: form-craft-backend
    ports:
      - '3001:3001'
    networks:
      - my_network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001']
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: form-craft-frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
