[backend]
start = "node dist/index.js"
install = "npm install"
build = "npm run build"
port = 3001

[frontend]
start = "nginx -g 'daemon off;'"
install = "npm install"
build = "npm run build"
port = 80
